# Site settings
title: hante's Blog
SEOTitle: hante's Blog
description: "안녕하세요. 개발자 한테의 블로그입니다."

# SNS settings      
github_username: devhante

# Build settings
paginate: 10                # nums of posts in one page
remote_theme : Huxpro/huxpro.github.io
